## **Lab 1 - Numpy and Pandas**
### S Kailash 18MIS1074 
### SWE4012 Machine Learning (L11+L12)
### Faculty : Dr. M Premlatha
### Date : 11th January 2022

#### In this lab session, we will be exploring the usage of Numpy and Pandas library. Let us first import them.

In [2]:
import numpy as np
import pandas as pd

We create two arrays for use, arr1 and arr2

In [11]:
arr1 = np.array([10,20,30,40,50,60])
print("1D array: ", arr1)
arr2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print("2D array 3*3: ", "\n",arr2)

1D array:  [10 20 30 40 50 60]
2D array 3*3:  
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In this section, we explore the attributes of the arrays.

In [12]:
print("About arr2:")
print("Type\t\t:" ,type(arr2))
print("Datatype\t:",arr2.dtype)
print("Shape\t\t:", arr2.shape)
print("Size\t\t:",arr2.size)
print("itemsize\t:",arr2.itemsize)
print("No. of dim\t:",arr2.ndim)
print("No. of bytes\t:", arr2.nbytes)

About arr2:
Type		: <class 'numpy.ndarray'>
Datatype	: int32
Shape		: (3, 3)
Size		: 9
itemsize	: 4
No. of dim	: 2
No. of bytes	: 36


In [13]:
arr3 = np.zeros((5,2), dtype=int)
arr4 = np.ones((3,4),dtype=float)
arr5 = np.eye(4,3)
arr6 = np.random.rand(3,2)
arr7 = np.random.randint(7,size=(2,6))
print("Zero Array \t:\n",arr3)
print("Arrays with unit values\t:\n",arr4)
print("Identity matrix\t:\n",arr5)
print("Random array\t\n",arr6)
print("Random integer array\t:\n" , arr7)

Zero Array 	:
 [[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
Arrays with unit values	:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity matrix	:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
Random array	
 [[0.70315442 0.63849731]
 [0.48149568 0.2320673 ]
 [0.66570186 0.8620893 ]]
Random integer array	:
 [[1 2 4 5 2 3]
 [4 6 2 5 6 4]]


In [14]:
arr8 = np.arange(1,12,3)
print("Array created with arange: \t\n",arr8)

Array created with arange: 	
 [ 1  4  7 10]


In [41]:
arr9 = np.linspace(1,10,30)
print("Array created using linspace requesting 30 elements within 1 to 10:\t\n",arr9)

Array created using linspace requesting 30 elements within 1 to 10:	
 [ 1.          1.31034483  1.62068966  1.93103448  2.24137931  2.55172414
  2.86206897  3.17241379  3.48275862  3.79310345  4.10344828  4.4137931
  4.72413793  5.03448276  5.34482759  5.65517241  5.96551724  6.27586207
  6.5862069   6.89655172  7.20689655  7.51724138  7.82758621  8.13793103
  8.44827586  8.75862069  9.06896552  9.37931034  9.68965517 10.        ]


Accessing elements of the arrays

In [16]:
arr10 = np.array([[10,20,30,40,50],[6,7,8,9,10],[110,120,130,140,150],[16,17,18,19,20]])
print(arr10)
print("Row 2:",arr10[1,:])
print("Column 5:",arr10[:,4])
print("Column 2:",arr10[:,3])
print("Elements 7,8,12,13 :\n", arr10[0:3,1:3])
print("All elements: \n",arr10[::])
print("Strides:\n",arr10[0::2,1:3])

[[ 10  20  30  40  50]
 [  6   7   8   9  10]
 [110 120 130 140 150]
 [ 16  17  18  19  20]]
Row 2: [ 6  7  8  9 10]
Column 5: [ 50  10 150  20]
Column 2: [ 40   9 140  19]
Elements 7,8,12,13 :
 [[ 20  30]
 [  7   8]
 [120 130]]
All elements: 
 [[ 10  20  30  40  50]
 [  6   7   8   9  10]
 [110 120 130 140 150]
 [ 16  17  18  19  20]]
Strides:
 [[ 20  30]
 [120 130]]


Image mask - returns elements which match with corresponding mask value = 1

In [18]:
arr11 = np.array([1,2,3,4,5,6,7,8,9])
mask = np.array([0,1,0,1,1,0,1,0,0],dtype=bool)
print(arr11[mask])

[2 4 5 7]


In [19]:
arr12 = np.array([[1,2,3,4,5],[6,7,8,9,9]])
print(arr12)
print("Sum \t:",np.sum(arr12))
print("Sum \t:",np.sum(arr12,axis=0))
print("Prod \t:",np.prod(arr12))
print("Prod \t:",np.prod(arr12,axis=0))
print("Minimum \t:",np.min(arr12,axis=0))
print("Maximum \t:",np.max(arr12,axis=0))
print("Mean \t:",np.mean(arr12,axis=0))
print("Variance \t:",np.var(arr12,axis=0))
print("Standard Deviation \t:",np.std(arr12,axis=0))
print("Average \t:",np.average(arr12,axis=0))
print("Weighted Average \t:",np.average(arr12,weights=[1,2,3,4,5],axis=1))

[[1 2 3 4 5]
 [6 7 8 9 9]]
Sum 	: 54
Sum 	: [ 7  9 11 13 14]
Prod 	: 3265920
Prod 	: [ 6 14 24 36 45]
Minimum 	: [1 2 3 4 5]
Maximum 	: [6 7 8 9 9]
Mean 	: [3.5 4.5 5.5 6.5 7. ]
Variance 	: [6.25 6.25 6.25 6.25 4.  ]
Standard Deviation 	: [2.5 2.5 2.5 2.5 2. ]
Average 	: [3.5 4.5 5.5 6.5 7. ]
Weighted Average 	: [3.66666667 8.33333333]


In-built mathematical,statistical and vector operations in numpy.

In [21]:
arr13 = np.array([1,2,3])
arr14 = np.array([4,5,6])
arr15 = arr13+arr14
arr16 = arr13 - arr14
print("Summation:\t",arr15)
print("Difference:\t",arr16)

arr16+=5
print("Previous output after adding 5:",arr16)

###  Try other operations
#add 10 to all elements of arr14

arr14+=10
print("Updated array 14",arr14)
arr15-=5
print("Updated array 15",arr15)
arr13*=3
print("Updated array 13",arr13)




Summation:	 [5 7 9]
Difference:	 [-3 -3 -3]
Previous output after adding 5: [2 2 2]
Updated array 14 [14 15 16]
Updated array 15 [0 2 4]
Updated array 13 [3 6 9]


In [38]:
arr17=np.array([1,2])
arr18=np.array([1,1])
result1 = arr17 == arr18
print(result1)

### Try other relational operations <<result2 to result6
result2 = arr17>arr18
result3 = arr17<arr18
result4 = arr18 == arr18
result5 = arr17 >= arr18
result6 = arr17 <= arr18

print("Array17 > Array18 ?",result2)
print("Array17 < Array18 ?",result3)
print("Array18 == Array18 ?",result4)
print("Array17 >= Array18 ?",result5)
print("Array17 <= Array18 ?",result6)


[ True False]
Array17 > Array18 ? [False  True]
Array17 < Array18 ? [False False]
Array18 == Array18 ? [ True  True]
Array17 >= Array18 ? [ True  True]
Array17 <= Array18 ? [ True False]


Trigonometrical Operations

In [26]:
arr17 = np.array([15,30,45,90])
result7 = np.sin(arr17)
print("Sin values:\t",result7)
result8 = np.log(arr17)
print("Log value:\t",result8)
arr171 = np.array([180,360,540,720])
### Try other operations
result9 = np.cos(arr17)
result10 = np.arcsin(arr18)
result11 = np.tan(arr17)
result12 =  np.arccos(arr18)
result13 = np.arctan(arr18)
print("Cosine ",result9)
print("Sine inverse ",result10)
print("Tangent",result11)
print("Cosine inverse",result12)
print("Tangent inverse ",result13)

Sin values:	 [ 0.65028784 -0.98803162  0.85090352  0.89399666]
Log value:	 [2.7080502  3.40119738 3.80666249 4.49980967]
Cosine  [-0.75968791  0.15425145  0.52532199 -0.44807362]
Sine inverse  [1.57079633 1.57079633]
Tangent [-0.8559934  -6.4053312   1.61977519 -1.99520041]
Cosine inverse [0. 0.]
Tangent inverse  [0.78539816 0.78539816]


In [34]:
#do the above commands
a=np.array([20,30,50,40])
aa = np.array([10.4,11.1,14.9,17.83,19.99])
print("Subtract 2,",np.subtract(a,2))
print("Multiply 3",np.multiply(a,3))
print("Divide by 4",np.divide(a,4))
print("Raise to power 5",np.power(a,5))

a1=np.array([1,3,5,7,9,11])
a2=np.array([2,4,6,8,10,12])

print("Add a1 and a2",np.add(a1,a2))
print("Subtract a1 and a2",np.subtract(a1,a2))
print("Multiply a1 and a2",np.multiply(a1,a2))
print("Divide a1 and a2",np.divide(a1,a2))
print("Raise a1 to a2's power",np.power(a1,a2))
print("Does a1 equals a2? ",np.array_equal(a1,a2))
print("Sqaure root of all elements of a",np.sqrt(a))
print("Round off all elements of aa",np.round(aa))

Subtract 2, [18 28 48 38]
Multiply 3 [ 60  90 150 120]
Divide by 4 [ 5.   7.5 12.5 10. ]
Raise to power 5 [  3200000  24300000 312500000 102400000]
Add a1 and a2 [ 3  7 11 15 19 23]
Subtract a1 and a2 [-1 -1 -1 -1 -1 -1]
Multiply a1 and a2 [  2  12  30  56  90 132]
Divide a1 and a2 [0.5        0.75       0.83333333 0.875      0.9        0.91666667]
Raise a1 to a2's power [          1          81       15625     5764801  -808182895 -1192716655]
Does a1 equals a2?  False
Sqaure root of all elements of a [4.47213595 5.47722558 7.07106781 6.32455532]
Round off all elements of aa [10. 11. 15. 18. 20.]


In [35]:
#do the above
print("Sum of all elements",np.sum(a))
print("Minimum of a",a.min())
print("Maximum of a",a.max())
print("Variance of a ",np.var(a))
print("Standard deviation of a ",np.std(a))
print("Correlation coefficient of a",np.corrcoef(a))

Sum of all elements 140
Minimum of a 20
Maximum of a 50
Variance of a  125.0
Standard deviation of a  11.180339887498949
Correlation coefficient of a 1.0


In [37]:
ar = np.array([[1,2,3,5],[7,8,9,10],[11,23,32,14]])
sum_value = np.sum(ar)
columnSum = np.sum(ar, axis = 0)
rowSum = np.sum(ar, axis = 1)
print(sum_value)
print(columnSum)
print(rowSum)

125
[19 33 44 29]
[11 34 80]


We can see that sum() returns sum of all elements, along axis0 returns the sum of columns, and along axis1 returns sum of rows.

### And with that, we finish Numpy. Let us move on to Pandas.

Pandas and dataframe usage :

We will be loading the famous iris dataset from GitHub and displaying the head and tail. The dataframe contains 5 columns - 
 *sepal_length, sepal_width, petal_length, petal_with,species*
of the Iris flower as classified. 

In [40]:
iris = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
print(iris.head())
print(iris.tail())

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica
